packaging_format = 2

id = "13ft"
name = "13ft"
description.en = "Bypass paywall by acting as GoogleBot"
description.fr = "Contourner les paywall en vous faisant passer pour GoogleBot"

version = "0.3.3~ynh1"

maintainers = ["Lapineige"]

[upstream]
license = "MIT"
code = "https://github.com/wasi-master/13ft"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/wasi-master/13ft/archive/refs/tags/v0.3.3.tar.gz"
        sha256 = "ff9ed6da73dace850bdf04c9fa66a80c62ed779053d7ce0d7f754ac9020b6879"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]
    main.default = 5000

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "python3-venv, python3-pip"
