packaging_format = 2

id = "13ft"
name = "13ft"
description.en = "Bypass paywall by acting as GoogleBot"
description.fr = "Contourner les paywall en vous faisant passer pour GoogleBot"

version = "0.2.3~ynh1"

maintainers = ["Lapineige"]

[upstream]
license = "MIT"
code = "https://github.com/wasi-master/13ft"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/13ft"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/wasi-master/13ft/archive/refs/tags/v0.2.3.tar.gz"
        sha256 = "d03abfded671fad157a883e348a7c5a2f21b251a592317f8208c9fc190ecbfde"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "python3-venv, python3, python3-pip"
